#!/usr/bin/env python

import os
import sys
import keyring

from playkit.project import ANSIBLE_PLAYKIT_VAULT_SERVICE_NAME

if __name__ == "__main__":
    project_name = os.path.basename(os.path.dirname(os.path.realpath(__file__)))
    password = keyring.get_password(ANSIBLE_PLAYKIT_VAULT_SERVICE_NAME, project_name)
    if password is None:
        sys.stderr.write("No password for project '{}' in keyring\n".format(project_name,))
        sys.exit(1)
    else:
        sys.stdout.write(password)

